version: '3'

services:
  spark-worker:
    image: terracoil/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2

    volumes:
      - ./data:/data
    depends_on:
      - spark-master
#    deploy:
#      resources:
#        limits:
#          memory: 4G

  spark-master:
    image: terracoil/spark:latest
    build: .
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark master
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/data
#    deploy:
#      resources:
#        limits:
#          memory: 4G




#version: '3'
#
#services:
#  spark:
#    image: terracoil.spark:3.5.1
#    environment:
#      - SPARK_MODE=master
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
#    platform: linux/amd64
#    ports:
#      - "8080:8080"  # Spark Web UI
#      - "7077:7077"  # Spark master
#    volumes:
#      - ./data:/home/windfox/spark_data  # Mount a local directory to the container for persistent storage
#  spark-worker:
#    image: terracoil.spark:3.5.1
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=1
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
#      - ./data:/home/windfox/spark_data  # Mount a local directory to the container for persistent storage