[tool.poetry]
name = "python-git-steven"
version = "0.1.0"
description = "Python setup for python examples and spikes"
authors = ["Steven Miers <steven.miers@gmail.com>"]
license = "Whatever"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyspark = {extras = ["connect"], version = "^3.5.1"}
numpy = "^1.26.4"
scikit-learn = "^1.4.2"
setuptools = "^69.5.1"
pandas = "^2.2.2"
pyarrow = "^15.0.2"
grpcio = "^1.62.2"
google-api-python-client = "^2.126.0"
grpcio-status = "^1.62.2"
nltk = "^3.8.1"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.1.6"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
